### ISSUE TITLE
UD to Apertium tags mapping

### ISSUE THREAD

**Issue by oserikov** [NIS-2018-CROSS-M/cross-lingual-morph-analysis#9]

**Comment by erba994** [comment]
Macedonian, Russian and Belarusian fixed

**Comment by nstsj** [comment]
hi guys, 
 a new doc is created -- new_tags.txt (see in develop branch) or [here](https://github.com/NIS-2018-CROSS-M/cross-lingual-morph-analysis/blob/develop/DATA/new_tags.txt)

feel free to contribute ur tag fixes and new issues there

**Comment by nstsj** [comment]
finished Croatian tag decyphering :)

**Comment by nstsj** [comment]
updated new_tags.txt  in develop branch

**Comment by erba994** [comment]
@nstsj I'll finish working on hr and sr, if you are planning to work tonight start from the remaining languages

**Comment by nstsj** [comment]
Ukranian, Slovenian, Polish updated in new_tags.txt (see develop)
